import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const font = Nunito ({ subsets: [ "latin" ] });

export const metadata: Metadata = {
   title      : "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
                                      children,
                                   }: Readonly<{
   children: React.ReactNode;
}>) {
   const SIGN_OUT_URL = process.env.NEXT_PUBLIC_CLERK_SIGN_OUT_URL;

   return (
      <ClerkProvider afterSignOutUrl={SIGN_OUT_URL}>
         <html lang="en">
         <body className={font.className}>{children}</body>
         </html>
      </ClerkProvider>
   );
}